### ISSUE TITLE
Are labels in narratable report handler right?

### ISSUE THREAD

**Issue by tailhook** [zkat/miette#106]
Here is the snippet from the test:
```rust
    let src = "source\n  👼🏼text\n    here".to_string();
    let err = MyBad {
        src: NamedSource::new("bad_file.rs", src),
        highlight: (9, 6).into(),
    };
    let out = fmt_report(err.into());
    println!("Error: {}", out);
    let expected = r#"oops!
    Diagnostic severity: error
Begin snippet for bad_file.rs starting at line 1, column 1
snippet line 1: source
    label starting at line 1, column 1: this bit here
snippet line 2:   👼🏼text
snippet line 3:     here
diagnostic help: try doing it better next time?
diagnostic code: oops::my::bad
"#
```
The highlight (9, 6) should be on line 2 column 3 I think. No? Actually I've noticed this on my own example which is very similar, the span is on the middle of the 18th line, where snippet starts from 17th. But it prints "label starting at line 17, column 1" (so looks like sticks always to the first column of the first displayed line).

Am I misunderstanding narratable handler?

**Comment by zkat** [comment]
oh that's weird. That's definitely a bug, but I'm not sure what's causing it.
