### ISSUE TITLE
Provide `.context()` on `miette::Report`

### ISSUE THREAD

**Issue by tailhook** [zkat/miette#108]
Can we have `.context()` on `miette::Report` as an alias to `wrap_err`?

This is convenient to make [`fn_error_context`](https://docs.rs/fn-error-context/latest/fn_error_context/) work on `miette::Result` returning functions..

Note: both [`anyhow::Error`](https://docs.rs/anyhow/latest/anyhow/struct.Error.html#method.context) and [`failure::Error`](https://docs.rs/failure/0.1.8/failure/struct.Error.html#method.context) have such method (but don't have `wrap_err`).

**Comment by zkat** [comment]
I guess I'll take a PR to do this, if that's ok :)

**Comment by zkat** [comment]
wait, I looked into this more and... do we even need that PR? `.context()` and `.with_context()` are already defined for Result? See https://github.com/zkat/miette/blob/main/src/eyreish/context.rs#L66-L79

**Comment by tailhook** [comment]
Yes we need that, because `fn_error_context` does `map_err(|e| e.context(...))`. Most likely, the reason for that is that `.context` is a method, so you don't have to require users importing an extension trait. And extension maybe a problem if you use multiple of these libraries in the same file (one reason for that is to gradually migrate your code from one library to another)
