### ISSUE TITLE
README example is discontinuous

### ISSUE THREAD

**Issue by CAD97** [zkat/miette#111]
https://github.com/zkat/miette/blob/2649fd27c47893dc3ba2445a9932600d1b3d3e63/README.md#L82-L162

The presented output image is one from nu:

![miette error rendering of nu::parser::unsupported_operation](https://img.gs/czjpqfbdkz/full/https://raw.githubusercontent.com/zkat/miette/main/images/single-line-example.png)

but the example is instead for rendering

![miette error rendering of oops::my::bad](https://user-images.githubusercontent.com/5992217/152070441-dd068d84-24f7-4b61-8336-2214477bf53a.png)

(Sorry, I can't do the pretty terminal window rendering)

**Comment by MoskalykA** [comment]
Can I take care of that?

**Comment by zkat** [comment]
I don't see why not! Go for it :)
