### ISSUE TITLE
Use `Report` in `related`

### ISSUE THREAD

**Issue by tailhook** [zkat/miette#119]
Currently you can't put `Vec<Report>` into the `related` field, only concrete error. This is quite inconvenient in certain cases.

One option would be to make some way to agument `related`:
```rust
struct MultiError {
  #[related(Report)]
  related: Vec<Report>,
}
```
Or maybe more generic:
```rust
struct MultiError {
  #[related(AsRef)] // or #[related(as_ref)]
  related: Vec<Report>,
}
```
Or even more generic:
```rust
struct MultiError {
  #[related(|x| x.as_ref())]
  related: Vec<Report>,
}
```

It should also be possible to use [dtolnay's hack](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md). But I'm not sure how much complexity that adds to the derive.

What do you think?

**Comment by zkat** [comment]
hmmm. This is kinda confusing 😅 

Is there a specific use case where this is painful and the alternatives are no good?

**Comment by tailhook** [comment]
> hmmm. This is kinda confusing sweat_smile
> 
> Is there a specific use case where this is painful and the alternatives are no good?

I have a cli which does something along the lines of:
```rust
let errs = Vec::new();
parse_config().map_err(|e| errs.push(e)).ok();
find_files().map_err(|e| errs.push(e)).ok();
process_files().map_err(|e| errs.push(e)).ok();
if !errs.is_empty() {
    return Err(MyError { related: errs });
}
```
I could use an enum like this in `related`:
```rust
#[derive(Debug, thiserror::Error, miette::Diagnostic)]
enum InnerError {
    #[error(transparent)]
    #[diagnostic(transparent)]
    ParseConfig(ParseConfigError),
    #[error(transparent)]
    #[diagnostic(transparent)]
    FindFiles(FindFiles),
    #[error(transparent)]
    #[diagnostic(transparent)]
    ProcessFiles(ProcessFiles),
}
```
But this is quite inconvenient:
1. Those three stages are a bit more complex in reality so may have multiple kinds of errors
2. And the end result is the same anyway (i.e this `InnerError` adds no additional info to the error as it rendered)

So another workaround I've implemented is:
```rust
#[derive(miette::Diagnostic, Debug)]
#[diagnostic(transparent)]
pub struct Related(miette::Report);

pub struct OuterError {
    related: Vec<Related>,
}
```
But the problem with this, is I can't use `thiserror::Error + #[error(transparent)]` as `miette::Report` doesn't implement deref to `dyn Error`. And anyway this is a no-value-added wrapper.

Or do you see any better alternatives?

**Comment by zkat** [comment]
Hm. I guess supporting `Report` there is definitely worth a shot, if we can manage it?
