### ISSUE TITLE
Add anyhow/eyre interop example

### ISSUE THREAD

**Issue by virtualritz** [zkat/miette#123]
The docs state that `Report` is an *"`anyhow`/`eyre`-compatible error wrapper type"* I couldn't find any example showing how this works.

I expected to be able to call `into_diagnostic()` on `anyhow::Error` after reading this but this doesn't work.

An example would be highly appreciated – maybe add one for `eyre` too, while at it. Cheers!

**Comment by zkat** [comment]
Oh nono, what this means is that you can swap your `use eyre::Report` for `use miette::Report` and have that kinda work most of the time. Probably worth clarifying.

**Comment by virtualritz** [comment]
Yes, maybe something like:

> `Report` is a drop-in replacement error-wrapper type for `anyhow`/`eyre::Report` with similar/same semantics/ergonomics.

?

**Comment by virtualritz** [comment]
I am happy do a PR – i.e. change the `README` text similar to the above and add notes to the docs for `miette::Result/Report` and `miette!` regarding those being viable replacements for those in `anyhow`/`eyre`.

Just to clarify – what I understand:

1. `miette::Result` and `miette::miette!` are replacements for `anyhow::Result`/`eyre::Result` and `anyhow::anyhow!`/`eyre::eyre!`

2. `miette::Report` is a replacement for `eyre::Report`

Correct?

**Comment by zkat** [comment]
that's correct!

**Comment by virtualritz** [comment]
So, spent a bit of time on this (#124) – such a nice crate deserves polished docs. 🤩

**Comment by virtualritz** [comment]
Btw., is the 1st sentence of the `README` a Cordwainer Smith reference 'haiku'?

**Comment by zkat** [comment]
it's a reference to this tweet: https://twitter.com/TriciaLockwood/status/1108102037072433153
