### ISSUE TITLE
Could I use non-textual `SourceCode`?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [zkat/miette#129]
I'm working on an application that lets you graphically define machine learning pipelines (imagine drawing a flowchart on an interactive canvas) and I was thinking of something like `miette` for reporting diagnostics.

The thing with my application is that we aren't attaching diagnostics to specific sections from some source text, there isn't even any text/file to annotate, instead I'll be associating diagnostics with objects in memory and displaying pop-ups or changing the element's styling appropriately.

Do you have any suggestions for how I might manage the diagnostic's location information? Looking at the way the types are structured, I don't think my use case will be compatible with the existing [`SourceCode`](https://docs.rs/miette/latest/miette/trait.SourceCode.html) and [`SourceSpan`](https://docs.rs/miette/latest/miette/struct.SourceSpan.html) abstractions, will it?

**Comment by zkat** [comment]
I mean, if your end goal is to be able to print these things as text in the terminal and point to specific points, then yes, miette can handle it. The catch is that you need to figure out a good abstraction for _your_ SourceCode (which doesn't have to be plain text to start!) So, basically you need to figure out how to implement SourceCode in a way that makes sense for you, and you should be good. If you don't intend to ultimately represent the output as text of some form (even "graphical" text), then miette is probably not what you want :)
