### ISSUE TITLE
Make "backtrace" an optional dependency behind different feature

### ISSUE THREAD

**Issue by bartlomieju** [zkat/miette#132]
Hi!

Currently miette pulls `backtrace` crate if `fancy` feature set is enabled. While I like color output and all the eye-candy miette provides, I plan to use it explicitly without relying on "global hook" and thus don't have any need for `backtrace` dependency. Unfortunately currently `backtrace` is pulled if `fancy` feature set is enabled and thus brings a lot of dependencies that I would prefer to avoid:
```
[[package]]
name = "backtrace"
version = "0.3.64"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5e121dee8023ce33ab248d9ce1493df03c3b38a659b240096fcbd7048ff9c31f"
dependencies = [
 "addr2line",
 "cc",
 "cfg-if 1.0.0",
 "libc",
 "miniz_oxide",
 "object",
 "rustc-demangle",
]
```
Is there any way `backtrace` could be hidden behind a separate feature flag?

**Comment by zkat** [comment]
I'm happy to take a PR that adds a `fancy-no-backtrace` feature!

**Comment by bartlomieju** [comment]
> I'm happy to take a PR that adds a `fancy-no-backtrace` feature!

That'd be great, much appreciated 🙏
