### ISSUE TITLE
Automatically implement `Clone` on `NamedSource` if the underlying source code does

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [zkat/miette#163]
This came up in one of my projects: I want to be able to clone some `NamedSource` that I store centrally and use if an error comes up. In my case, I should probably implement my own NamedSource variant with `Rc`, but in general, it could be a nice feature to have a `Clone` implementation for `NamedSource` if the underlying `SourceCode` is also `Clone`. Though I'm not super familiar with specifying type bounds for contained dyn traits in the impl declaration instead of the field declaration, so I don't even know whether that's possible.

**Comment by zkat** [comment]
NamedSource is meant to be a pretty trivial convenience and would be super easy to duplicate if you want to add that + Clone constraint. But I don't think NamedSource itself should add it. 

I'll point out that SourceCode is implemented for Arc<SourceCode> though, and that might work for you right away without having to copy too much stuff around :)

**Comment by kleinesfilmroellchen** [comment]
Yeah I'm passing my source code behind Arc now, I think your reasoning here is fine with me.
