### ISSUE TITLE
JSON renderer does not render causes

### ISSUE THREAD

**Issue by leonbreedt** [zkat/miette#187]
Hello there,

It looks like rendering causes was not implemented for the JSON renderer.

```plaintext
Error: up::error::sql

  × SQL query failed
  ├─▶ error returned from database: operator does not exist: uuid = text
  ╰─▶ operator does not exist: uuid = text
```

Example JSON output:

```json
{"message": "SQL query failed","code": "up::error::sql","severity": "error","labels": [],"related": []}
```

I am not sure if this was an intentional omission, but it would be helpful to provide additional context if it were there, especially in log aggregators.

Cheers!

**Comment by zkat** [comment]
This seems like it would be a great addition, tbh. It was definitely not intentional (not on my part, though the JSON renderer was a contribution). If you're up to it, I'd love a PR to do this?

**Comment by leonbreedt** [comment]
@zkat: I've taken a stab in PR #188.
