### ISSUE TITLE
License not 100% compatible with Rust recommendations

### ISSUE THREAD

**Issue by Finomnis** [zkat/miette#194]
## Problem

The RUST API guidelines [recommend against](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) using `Apache-2.0` as the only license for crates.

## Solution

[Add the MIT license as well.](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive)

This is not an aggressive demand for a license change, I just wanted to bring this to your attention as I also just recently learned the recommendation. Hope this helps increase your user base even further ;)

**Comment by zkat** [comment]
I prefer the Apache license specifically for its added patent-related clauses, plus its more stringent requirements on attribution. I am aware of the Rust ecosystem's tendencies towards dual licensing but I don't care much for doing that with two separate permissive licenses, esp if one doesn't offer patent protection.
