### ISSUE TITLE
get fancy reporting in tests

### ISSUE THREAD

**Issue by mimoo** [zkat/miette#195]
Is it possible to use miette's fancy reporting feature in tests? I can do it from main but not sure how that would work in a test

**Comment by zkat** [comment]
You should be able to just `Report::new(err).to_string()` if I remember correctly?

**Comment by mimoo** [comment]
actually as long as I `unwrap` a `miette::Result` it works!

**Comment by mimoo** [comment]
Actually, it sometimes work, and sometimes doesn't work :| I'm not sure why.

doing `to_string()` on a `miette::Error` only prints the `#[error("oops!")]` field of the error.

**Comment by Shfty** [comment]
In case anyone stumbles across this, the `Display` implementation for `Report` yields a simple print, whereas its `Debug` implementation outputs fancy formatting.

I assume this is for compatibility with the debug formatter used by Result::unwrap.

Either way, it would be nice if non-main usage were noted in the top level documentation.

**Comment by zkat** [comment]
I’ll take a PR for doc improvements if you’re up for it!
