### ISSUE TITLE
Can't create report from boxed diagnostic (impl Diagnostic for Box<dyn Diagnostic [ + Send + Sync]>?)

### ISSUE THREAD

**Issue by sunshowers** [zkat/miette#212]
Hi!

I noticed that it doesn't seem to be possible to construct a `Report` from a boxed dynamic diagnostic. This seems a bit unfortunate, and should be fixable if we implement `Diagnostic` for `Box<dyn Diagnostic>` and the `Send` and `Sync` variants.

What do you think? Happy to submit a patch for this.

**Comment by zkat** [comment]
I'm not opposed to it! I have this weird feeling that there was a reason this wasn't done before, but it's been too long and I can't remember. Oh well. One way to find out, I guess :)

**Comment by sunshowers** [comment]
Ah so you're right -- there are a number of issues that crop up if I try to do this:

## Conflict with `From` impls

The code conflicts with this:

```rust
impl<T: Diagnostic + Send + Sync + 'static> From<T> for Box<dyn Diagnostic + Send + 'static> {
    fn from(diag: T) -> Self {
        Box::<dyn Diagnostic + Send + Sync>::from(diag)
    }
}
```

We could potentially remove these impls in a breaking change to miette -- I haven't really seen them anywhere else, generally people use `Box::new()` to create boxed dynamic traits (e.g. `Box::new(error)` to create a `Box<dyn Error>`).

## `miette_kind()` pseudo-specialization no longer works

Miette has an implementation of something that looks like specialization in https://github.com/zkat/miette/blob/3f9da04b866f3fd90f88e7e60f9fb7a322aef568/src/eyreish/kind.rs. This specialization no longer works all the time. I haven't dug into why yet.

After encountering these I decided to work around it in my own code by just returning a `Report` where I'd have returned a `Diagnostic` in the past.

I'll put up what I did shortly.

**Comment by sunshowers** [comment]
However, having written this out, I think that a BoxedDiagnostic newtype wrapper would work for this.

**Comment by sunshowers** [comment]
Oh, this already works, putting up a small PR in a bit.
