### ISSUE TITLE
Humanize panic handling?

### ISSUE THREAD

**Issue by zkat** [zkat/miette#22]
https://github.com/rust-cli/human-panic seems neat. Is this something miette should do? I'm not sure

**Comment by drmason13** [comment]
If it helps, I think this is safe to consider out of scope for Miette.

Having said that, it would be nice to add a mention to the README. Something like:
> While you're considering beautiful error outputs for human users of you application...
> Have you considered what panic messages look like?
> Miette doesn't alter Rust's default panic messages.
> You could use a crate like [human-panic](https://github.com/rust-cli/human-panic) which does, or even write your own [`std::panic::set_hook`](https://doc.rust-lang.org/std/panic/fn.set_hook.html) to gain the most flexibility.

I was a bit surprised that the message in human-panic is hardcoded, see: https://github.com/rust-cli/human-panic/issues/54. I wouldn't want to force the exact text they use on users of Miette. Could be a good contribution to human-panic to add a custom message feature (for [2.0.0](https://github.com/rust-cli/human-panic/issues/46)).
