### ISSUE TITLE
Switching out `atty`?

### ISSUE THREAD

**Issue by Porges** [zkat/miette#228]
Would you accept a PR to switch out `atty` for something else? This would also affect `supports_unicode` and `supports_hyperlinks`.

There’s been an audit failure on `atty` for a while now which requires explicit suppression if you’re using something like `cargo-audit` or `cargo-deny`. 

As to replacements, `is-terminal` seems to have been picked up by several projects such as `clap`.

**Comment by zkat** [comment]
yes, I've already accepted a PR to `supports-color` to make this change, so I'm happy to take PRs for the other three.

**Comment by Porges** [comment]
Opened:
- https://github.com/zkat/supports-hyperlinks/pull/3
- https://github.com/zkat/supports-unicode/pull/4

I also put [a comment](https://github.com/zkat/supports-color/pull/10#issuecomment-1360140366) on the `supports-color` PR to suggest removing the indirection through the `Stream` type and instead expose the function for any `IsTerminal` to make it more generally useful.

**Comment by gavrilikhin-d** [comment]
Should this issue be closed?

**Comment by Porges** [comment]
`std::io::IsTerminal` landed in 1.70.0, so we could now also drop the `is-terminal` dependencies.

**Comment by zkat** [comment]
Thanks for these PRs. I'm gonna take care of this sometime soon, since it involves a coordinated release of several semver-major versions.

**Comment by Nahor** [comment]
This can be closed now (fixed in e5c7ae4)
