### ISSUE TITLE
Allow the inner source type of a `NamedSource` to be borrowed directly

### ISSUE THREAD

**Issue by esoterra** [zkat/miette#236]
I would like to be able to use `&NamedSource` as the input to parsing and lexing functions that use and borrow from the source already stored in the `NamedSource::inner()` instead of passing another copy.

Based on the discussion in #235, we could do this by making `NamedSource` generic over the inner source type which could simplify the API for a basic parse function to something like this:
```rust
pub fn parse(source: &NamedSource<String>) -> Result<Tokens<'_>> {
   let chars = source.inner().char_indices();
   ...
}
```

**Comment by kallisti-dev** [comment]
Submitted a PR for this: #254 . See my comment there for notes about compatibility. I'll look into a backwards compatible version of this over the next few days. Feedback would be appreciated.
