### ISSUE TITLE
More controlability for the `label`

### ISSUE THREAD

**Issue by attila-lin** [zkat/miette#238]
Hi.

It's really nice work! I used it in my language lint cli-tool and `miette` worked really nicely with my error handler choice - `thiserror`.

Currently, I'm trying to upgrade my tool to a [lsp](https://microsoft.github.io/language-server-protocol/), and I have some trouble.

As you know, I want to provide the client with the [diagnosis](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic), and you can see the `Range` define [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range), which need to provide more information.

I have these pieces of information already but I have to change it to `(usize, usize)`(the start and the length) to fit the `label` definition.

So may I have some trait like `IntoLabel`, and if I impl it, the label will work, then I don't need to spread the errors or add new fields for cli and lsp?

**Comment by zkat** [comment]
I'm having a hard time understanding what you're missing here. The Diagnostic object in lsp seems to be almost a 1:1 translation to a miette::Diagnostic (aside from the specific format of the range, but there's already a utility provided to do that conversion)

**Comment by attila-lin** [comment]
I may missed it. Can you tell me the utility's name?

lsp Range need the line number and the character count. Diagnostic provide the start offset and length.

**Comment by zkat** [comment]
@attila-lin https://docs.rs/miette/latest/miette/struct.SourceOffset.html#method.from_location

So in order to give miette a `SourceSpan` from your LSP `Range`, you would do something like:

```rust
#[derive(miette::Diagnostic)]
struct MyDiag {
  #[source_code]
  src: String,
  #[label("bad here")]
  span: miette::SourceSpan,
}
let start = miette::SourceOffset::from(your_source_code, lsp_range.start.line, lsp_range.start.column);
let end = miette::SourceOffset::from(your_source_code, lsp_range.end.line, lsp_range.end.column);
let diag = MyDiag { src: your_source_code, span: (start, end).into()) }
```

**Comment by attila-lin** [comment]
Thank you for your response. Get it! It would work~

But I have some different conditions.

First, I don't have my `source_code` in error (and also in lint checks), because I will try to test and create a lot of lint results for one file. In the lint checks, I just need an AST tree and no need the source.

I will create do the lint check like this
```rust
/// lint A result
#[derive(miette::Diagnostic)]
struct LintAError {
    #[lable("this is bad for lint A")]
    span: (usize, usize)
}

/// lint B result
#[derive(miette::Diagnostic)]
struct LintBError {
    #[lable("this is bad for lint B")]
    span: (usize, usize)
}

let mut reports = Vec::new();

// Do some check

reports.push(miette::Report::from(lint_a_error));
reports.push(miette::Report::from(lint_b_error));
// .. more lint result

for report in reports {
    println!("{:?}", report.with_source_code(code));
}
```

It works, but hard for me to add lsp support.

Second, I think we may have a better ergonomics like this.

```rust
/// lint A result
#[derive(miette::Diagnostic)]
struct LintAError {
    #[lable("this is bad for lint A")]
    span: MyRange
}

/// lint B result
#[derive(miette::Diagnostic)]
struct LintBError {
    #[lable("this is bad for lint B")]
    span: MyRange
}


struct MyPosition {
    bytes: usize,
    line: usize,
    character: usize
}

struct MyRange {
    start: MyPosition,
    end: MyPosition
}


/// It will work for `lable` macro
impl IntoSourceSpan for MyRange {
    fn into_source_span() -> SourceSpan {
        // do some convert
        
    }
}

// If i'm working for lsp, I can add my trait
impl IntoLspRange for MyRange {
    //
}

```

What's your opinion?

**Comment by zkat** [comment]
the idea is that you would have source code when you _create_ your linting errors. Do you not have source code at that point? Is it possible to create the _spans_ when you're scanning through the source code?
