### ISSUE TITLE
Update miette-derive syn dependency to syn 2

### ISSUE THREAD

**Issue by jtroo** [zkat/miette#243]
Syn 2 was released recently and some crates, e.g. thiserror, are already migrated. To reduce clean compile times, should upgrade dependency to syn 2.

**Comment by zkat** [comment]
You wanna send me a PR for this? :)

**Comment by jtroo** [comment]
Doing a few minutes of investigation, it looks like it's a nontrivial change, to be expected since it's a major version update. It also looks like some tests are failing, just having checked out the code without trying to upgrade version yet, so that might be an issue with testing changes. I'll see how it goes when I find more time, no promises though 😅
