### ISSUE TITLE
Use serde

### ISSUE THREAD

**Issue by gavrilikhin-d** [zkat/miette#260]
Could you make your `SourceOffset`, `SourceSpan`, `Severity`, `LabledSpan` and other types to implement `Serialize` and `Deserialize`?
Now you need to use builtin types instead of them to have serialization autoimplemented:
```rs
#[derive(Debug, Error, Diagnostic, Serialize, Deserialize, PartialEq, Eq, Clone)]
#[error("expected '{expected}'")]
pub struct Expected {
    pub expected: String,
    #[label("{expected}")]
    pub at: usize, // This is auto serialized/deserialized
}
```
So you can't just write:
```rs
#[derive(Debug, Error, Diagnostic, Serialize, Deserialize, PartialEq, Eq, Clone)]
#[error("expected '{expected}'")]
pub struct Expected {
    pub expected: String,
    #[label("{expected}")]
    pub at: SourceOffset, // Doesn't work. Need to implement manually
}
```

**Comment by kleinesfilmroellchen** [comment]
Since serde is a large dependency, this should most definitely be an optional or opt-out dependency for anyone who doesn't need it.

**Comment by zkat** [comment]
This seems reasonable, as long as it's hidden behind a non-default `serde` flag. I can't really do a lot of stuff myself right now, but I probably have time to review/merge a PR if someone contributes it.

**Comment by gavrilikhin-d** [comment]
Ok, I will create a PR on these weekends

**Comment by gavrilikhin-d** [comment]
This one looks related: #245
