### ISSUE TITLE
Constify `SourceOffset` and `SourceSpan`

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [zkat/miette#261]
Since these are POD types containing simple integers, most of their code can be const. Specifically, all non-trait functions of `SourceSpan` and at least `SourceOffset::offset`. The other ones may use functions that are only const on nightly, and `SourceOffset::from_current_location` can most certainly not be const. However, these few would allow us to construct constant source spans and offsets, and extract their basic properties, which is my use case.

**Comment by zkat** [comment]
I'd take a PR for this! This seems like a good idea :)
