### ISSUE TITLE
Do I need to fill the source content of NamedSource by myself?

### ISSUE THREAD

**Issue by BppleMan** [zkat/miette#271]
In the example in the repo README, the src of the NamedSource is a hardcoded source

```rust
let src = "source\n text\n here".to_string();
```
Does this mean that I need to hardcode some current error context codes for each error, and calculate the offset that needs to be labeled by myself?

I saw the SourceCode in the proc-macro, just got the ident, it seems that there is no step to get the source code file?

**Comment by zkat** [comment]
A `SourceCode` is anything that implements the `SourceCode` trait. If you want to work off a file more dynamically, you'll need to write an implementation for it. All you need to be able to do is tell miette how to read a specific span from it: https://github.com/zkat/miette/blob/main/src/protocol.rs#L211-L231

**Comment by BppleMan** [comment]
I always thought that miette was a crate like coloreyre. Later I figured out that miette is suitable for some lexical analysis or as a language interpreter. I'm not sure. I always want to let miette capture the context part of the current rs code to use in some fancy output can be displayed when panic, this is probably some misunderstanding of mine
