### ISSUE TITLE
Best way to offer "breadcrumbs"

### ISSUE THREAD

**Issue by the-eater** [zkat/miette#284]
I am currently writing an application that parses config files which optionally are able to include other config files (by chance, they are written in `kdl`; I am running the zkat stack I guess)

However if an error in one those config files occurs, I want to offer breadcrumbs of where it was included, what would be the best way to achieve this?

I am currently trying to use `#[related]` but it now looks as if every include is an error lol

```
  × Found cyclic include for "pneumail-mta/resources/lol.kdl" at pneumail-mta/resources/oof.kdl:0:8 which was entered at pneumail-mta/resources/nyaa.kdl:0:8
   ╭─[pneumail-mta/resources/oof.kdl:1:1]
 1 │ include "lol.kdl"
   ·         ────┬────
   ·             ╰── included again here
   ╰────

Error:   × File was selected by
   ╭─[pneumail-mta/resources/nyaa.kdl:1:1]
 1 │ include "oof.kdl"
   ·         ────┬────
   ·             ╰── included here
   ╰────
Error:   × File was selected by
   ╭─[pneumail-mta/resources/lol.kdl:1:1]
 1 │ try-include "nyaa.kdl"
   ·             ─────┬────
   ·                  ╰── included here
   ╰────
Error:   × File was selected by
   ╭─[pneumail-mta/resources/config.kdl:1:1]
 1 │ include "lol.kdl"
   ·         ────┬────
   ·             ╰── included here
 2 │ 
   ╰────
```

Would there be a better or different way to offer these "breadcrumbs"?

**Comment by the-eater** [comment]
I found a really disgusting way to get a bit better looking results, which is making the breadcrumb "errors" start with `\r` so the whole error prefix gets yeeted, but this works only on consoles lol

**Comment by zkat** [comment]
You have basically three choices right now:

1. use the "related" diagnostics feature and stuff your breadcrumbs into a "related" field.
2. use `diagnostic_source`, which will "nest" the recursive source diagnostics in the "breadcrumb"
3. write your own logic for printing multiple diagnostics according to your specific needs.

The difference between 1 and 2 is mostly whether you want things to look nested or not.

**Comment by the-eater** [comment]
Ah okay, yeah 3 is the option that, to me makes most "reader ergonomic" sense, but `miette` doesn't expose the "annotated source code struct" so I guess the best choice for me is to double dip `miette` _and_ `ariadne`. I was just hoping to avoid that, as `knuffel` already uses `miette`

anyhow, thanks :)
