### ISSUE TITLE
help message passthrough

### ISSUE THREAD

**Issue by vic1707** [zkat/miette#296]
hello, I'm trying to get a different `help` field for each of my `ErrorKind` variants but can't figure out how to do it nor if it's possible.

```rs
#[derive(Debug, Eq, PartialEq, thiserror::Error, Diagnostic)]
#[error("{kind}")]
pub struct Error {
    #[help(transparent)] // this enable `help` message to be shown
    kind: ErrorKind,
    #[label("here")]
    span: SourceSpan,
    #[source_code]
    src: String,
}

#[derive(Debug, Eq, PartialEq, thiserror::Error, Diagnostic)]
#[non_exhaustive]
pub enum ErrorKind {
    #[error("Unexpected end of expression")]
    #[help("Huston, we are missing something here !")]
    UnexpectedEndOfExpression,
    #[error("Unexpected token: `{0}`")]
    #[help("Maybe remove it ?")]
    UnexpectedToken(char),
    #[error("Malforned number: `{0}`")]
    #[help("You can't have two dots in a number")]
    MalformedNumber(String),
    #[error("Illegal character: `{0}`")]
    #[help("Maybe remove it ?")]
    IllegalCharacter(char),
    #[error("Expected token: `{0}`")]
    #[help("Try inserting `{0}` here")]
    // #[diagnostic(help("Try inserting `{0}` here"))] -- this other version doesn't do anything
    ExpectedToken(char),
}
```

the best output I could get was with this code where I get
<img width="425" alt="image" src="https://github.com/zkat/miette/assets/28602203/905d1632-4d5d-4075-9755-cda06a09132b">

As you can see the `help` message is the same as the `error` one, not the help one I provided.
Can someone enlighten me ?

**Comment by zkat** [comment]
In your case, I think the easiest thing to do is to implement `Diagnostic` manually. It's not a lot of work, and it would give you full flexibility to pass things through as needed.

So, do `#[diagnostic(help("blablabla"))]` for all your variants in `ErrorKind`, and use the regular derive macro, then `impl Diagnostic for Error` and forward the methods you want to forward. :)

**Comment by vic1707** [comment]
Okay thx I'll do that
