### ISSUE TITLE
`miette-derive` being required dependency

### ISSUE THREAD

**Issue by ManicMarrc** [zkat/miette#303]
Are there any reasons why `miette-derive` is a required dependency and not optional?
`miette-derive` is taking up a lot of my compile time but all I'm using is the `miette!` macro.

**Comment by zkat** [comment]
I would take a patch that adds miette-derive as a default, but optional feature

**Comment by zkat** [comment]
I don't know why github didn't close this issue. The related PR was merged. Thanks again.
