### ISSUE TITLE
Printing errors with an empty highlight span panics.

### ISSUE THREAD

**Issue by martica** [zkat/miette#31]
```
thread 'single_line_highlight' panicked at 'attempt to subtract with overflow', .../miette/src/printer/graphical_printer.rs:388:29
```

I can reproduce this with the existing test suite by changing the 4 to 0 here: https://github.com/zkat/miette/blob/7e76e2dea4adf0e4a1349e049495c1f5a0bdab87/tests/printer.rs#L44

**Comment by martica** [comment]
I can make a run at fixing this, if you can weigh in with what the behaviour should be in this case. Clamping the length to at least 1 when rendering seems like a straightforward solution, if that works for you.

**Comment by zkat** [comment]
Yeah, whatever works! I've been ~~ab~~using `.saturating_sub()` to avoid all sorts of weird off-by-ones, so maybe that's a good alternative here? Nice catch! And yeah, a PR is super welcome! :)

**Comment by martica** [comment]
Sound great.

I tried the saturating sub, but letting it go to zero width looks odd:
```
────[oops::my::bad]────────────────────

    × oops!

   ╭───[bad_file.rs:1:1] This is the part that broke:
 1 │ source
 2 │   text
   · 
   ·   ╰─ this bit here
 3 │     here

    ‽ try doing it better next time?
```

This is what it looks like if I clamp with the width to at least 1:
```
────[oops::my::bad]────────────────────

    × oops!

   ╭───[bad_file.rs:1:1] This is the part that broke:
 1 │ source
 2 │   text
   ·   ┬
   ·   ╰─ this bit here
 3 │     here

    ‽ try doing it better next time?
```

**Comment by zkat** [comment]
Hmm. What do you think about using an up-arrow when the width is 0, instead of an underline + clamping?
