### ISSUE TITLE
Is there a way to pull labels from a collection using proc macros?

### ISSUE THREAD

**Issue by KAAtheWiseGit** [zkat/miette#315]
Good day!

I have an enum with `#[derive(Diagnostic)]`.  I am trying to add an error type, which can have several spans sourced from a collection:

```Rust
pub enum ShellError {
    ...
    #[error("{0}")]
    #[diagnostic()]
    GenericError(
        String,
        #[label("{1}")]
        Vec<SourceSpan>,  // a vector with several spans
    ),
```

Is there a way to achieve this with proc macros?

**Comment by zkat** [comment]
Not right now, but being able to do this sounds great! :)
