### ISSUE TITLE
Thiserror W/ Miette how to display?

### ISSUE THREAD

**Issue by gluax** [zkat/miette#322]
Hey all,

I'm trying to leverage `miette`'s pretty printing with `thiserror`.

But I run into the case where when an error bubbles up, it only displays what's written in the error proc macro for an enum, and it doesn't display the source code blocks or anything.

Example

```rust
#[derive(Debug, miette::Diagnostic, thiserror::Error)]
enum Error {
    #[error("make command failed")]
    #[diagnostic(code(foo::command_make_error))]
    MakeCmd {
        cmd: &'static str,
        #[source_code]
        stderr: String,
    },
}
```

Produces an error like this, not printing the `source_code` block at all:

![image](https://github.com/zkat/miette/assets/16431709/6ab9f3ba-a370-480b-bc64-ac59ff9d729d)

I tried looking at the readme and other examples, but cannot figure out why this is the case.

Can someone explain how to make this work with `thiserror`?

**Comment by zkat** [comment]
https://github.com/zkat/miette?tab=readme-ov-file#-snippets you need to use labels

**Comment by gluax** [comment]
Ah, I see, thank you!!

So I can't attach multiple instances of arbitrary text(Strings/&'static str/etc) to be printed out, or have the code be dynamically set from a field?

**Comment by zkat** [comment]
Correct. You always need SourceCode + at least one label. But you can have a single label that's the span of your entire arbitrary string, if you want. Miette can do multiline spans
