### ISSUE TITLE
Implement SourceSpan as a trait

### ISSUE THREAD

**Issue by hhamud** [zkat/miette#323]
I already have a sourcespan-like struct that is sprinkled all over my code base and I was hoping to use this library as a way to prettify my errors but it would mean a complete refactor.

Is there a way around this or does this require what I hope it doesn't?

This is what I currently have:

```rust
#[derive(Debug, PartialEq, Clone)]
pub struct Token {
    pub token: String,
    pub token_kind: TokenKind,
    pub row: usize,
    pub column: Line,
    pub namespace: PathBuf,
}

#[derive(Debug, PartialEq, Clone)]
pub struct Line {
    pub start: usize,
    pub end: usize,
}

//...other code here
```

**Comment by zkat** [comment]
If your implementation is based on row + column instead of byte offset and length (which is what miette primarily uses), you can use [this utility method on `SourceOffset`](https://github.com/zkat/miette/blob/main/src/protocol.rs#L635-L653), combined with a `From` implementation (or so) to convert your `Token` struct into the necessary `SourceSpan`s.

Does that make sense?

**Comment by hhamud** [comment]
Thanks. I've managed to do as you say but it the labels don't render

<img width="869" alt="image" src="https://github.com/zkat/miette/assets/53880692/eaa38a63-e1be-4c0e-ac0a-d2b9423b851f">


and here is the snippet of code relating to that

<img width="953" alt="image" src="https://github.com/zkat/miette/assets/53880692/f2dee79a-6e34-4031-b7a7-52bc36d03d4e">

**Comment by zkat** [comment]
Labels don't render unless you specify a [`source_code`](https://github.com/zkat/miette/blob/main/src/protocol.rs#L52) for the error. You can do this either by either putting the relevant source code into the error and tagging it with `#[source_code]` (it can be anything that implements [`SourceCode`](https://github.com/zkat/miette/blob/7ff4f874d693a665af4df40f4e94505013e3e262/src/protocol.rs#L234), such as `String`, or any custom source representation you implement it for), or by [providing it at the very end, using `.with_source_code()`](https://github.com/zkat/miette/tree/7ff4f874d693a665af4df40f4e94505013e3e262#-delayed-source-code).

**Comment by zkat** [comment]
I think this was resolved in a satisfactory way, so I'm closing this.
