### ISSUE TITLE
Update owo-colors to v4?

### ISSUE THREAD

**Issue by sunshowers** [zkat/miette#336]
Hi Kat,

Congrats on the miette v6 release!

I was hoping to see owo-colors v4 in miette 6, but sadly that didn't happen. Would you be open to updating owo-colors now and releasing a v7? Now is the best time to do it because there will be minimal disruption from a new version.

Thanks!

**Comment by zkat** [comment]
Oh! Good plan. Yeah, I don't mind a quick second major release to bump that and maybe a couple of other versions I didn't check

Isn't there a cargo tool for seeing updates to all your deps?

**Comment by sunshowers** [comment]
cargo upgrade maybe?

**Comment by zkat** [comment]
apparently it was part of cargo-edit! This is done. New version coming in a bit.

**Comment by zkat** [comment]
7.0 has been published. Thanks for this heads-up! Enjoy :)

**Comment by sunshowers** [comment]
Thank you!
