### ISSUE TITLE
要是错误提示能使用中文输出就好了！

### ISSUE THREAD

**Issue by yaoxingpu** [zkat/miette#357]

**Comment by zkat** [comment]
现在的中文错误信息有什么问题吗？

**Comment by yaoxingpu** [comment]
您的意思是可以设置输出的错误信息让中文显示吗，我没找到呀

**Comment by zkat** [comment]
您可以将任何字符串设置为错误消息、标签和建议。 如果您用中文编写工具，则可以用中文编写所有内容。

如果您想要多语言支持，则必须使用自己的工具来检测用户的首选语言并据此更改字符串。 这超出了 miette 的范围。

**Comment by yaoxingpu** [comment]
好的，谢谢你

**Comment by zkat** [comment]
不客气！ 祝你今天过得愉快。
