### ISSUE TITLE
Implement `WrapError` for `Option`

### ISSUE THREAD

**Issue by jalil-salame** [zkat/miette#408]
`anyhow` [implements it's `Context` trait on options](https://docs.rs/anyhow/latest/anyhow/trait.Context.html#impl-Context%3CT,+Infallible%3E-for-Option%3CT%3E). This helps avoid some boilerplate:

```rust
use anyhow::Context;

let map = HashMap::from([("a", 1), ("b", 2), ("c", 3)]);
let _ = map.get("d").with_context(|| format!("Key 'd' was missing from map: {map:?}"))?;
```

Currently the best way to do this with `miette` is by using a `let else` then `bail!`:

```rust
use miette::bail;

let map = HashMap::from([("a", 1), ("b", 2), ("c", 3)]);
let Some(_) = map.get("d") else {
    bail!("Key 'd' was missing from map: {map:?}"));
};
```

I'm willing to implement this if desired

**Comment by zkat** [comment]
sounds good to me! go for it!
