### ISSUE TITLE
`.source_code()` and `.with_source_code()` methods for `Report`

### ISSUE THREAD

**Issue by zkat** [zkat/miette#64]
This will make it possible to delay providing `source_code` until the app is ready to provide it, which is a common pattern in compilers.

**Comment by tailhook** [comment]
Is the plan that source code specified by the method propagates to "related" errors? It may fix #99 for me.

**Comment by zkat** [comment]
Oh hey. I forgot I had this issue open.

Yes, this is the intention and I believe it would fix your issue :)
