### ISSUE TITLE
Feature Request: minimal or no output on an enum varient

### ISSUE THREAD

**Issue by Fishrock123** [zkat/miette#65]
This sounds a bit strange, but I have a cli handling CTRL+C, including from stdin prompts, and it would be nice if the error case for that could be more minimal than the rest.

**Comment by zkat** [comment]
I'll add this to the list of stuff to have (better) support for in miette 3.0.

 I was talking with someone about having another reporter, a `compact` reporter that doesn't do snippets (probably) but has much more compact output. I think this issue fits that nicely.

**Comment by Fishrock123** [comment]
Ok - I’m not meaning for all errors or all variants though. Mostly just for one or two variants that can have minimnal output (no separator lines, etc)

**Comment by zkat** [comment]
I think this is taken care of nicely by the new, much more compact syntax:

<img width="534" alt="Screen Shot 2021-09-21 at 21 22 45" src="https://user-images.githubusercontent.com/17535/134283157-1ad43c00-56f7-4af7-9fac-d61c5094098c.png">

**Comment by zkat** [comment]
vs when you actually have an error code:

<img width="577" alt="Screen Shot 2021-09-21 at 21 23 38" src="https://user-images.githubusercontent.com/17535/134283211-a0e174fe-2e29-4abd-ab2b-1ed35cfd06b3.png">
