### ISSUE TITLE
Why does NamedSource have a static lifetime?

### ISSUE THREAD

**Issue by jmackie** [zkat/miette#77]
Seems unncessary, unless I'm missing something (which is quite likely tbh)?

It's fine for test cases and examples, but for a real compiler use case source files won't be statically known 🙃 

Keep up the awesome work ❤️

**Comment by zkat** [comment]
The expectation is that "real" compilers will be using their own NamedSource implementation for stuff like this, and the static lifetime is so you can pass a slice of something in as the `source` without handing the NamedSource full ownership. Does that answer your q?

**Comment by jmackie** [comment]
Ahh okay fair enough, might be worth adding that to the docs? 

Thanks!
