### ISSUE TITLE
Creating SourceOffset with raw byte

### ISSUE THREAD

**Issue by BasixKOR** [zkat/miette#98]
I was trying to make an error reporting with this, and while I was able to create an offset for a start using `from_location`, I couldn't make the length offset with SourceOffset, meaning I can't make SourceSpan. (well, unless I go deep and transmute but that isn't valid option at all)

Can I make a `SourceOffset` instance with just a raw `usize`? Or is this API unavailable by design which means I can do this better?

**Comment by BasixKOR** [comment]
Unsure how did I missed this: https://docs.rs/miette/latest/miette/struct.SourceOffset.html#impl-From%3Cusize%3E

**Comment by zkat** [comment]
Glad I could help! ;)
