### ISSUE TITLE
Can renderer of related errors (optionally) preserve source code?

### ISSUE THREAD

**Issue by tailhook** [zkat/miette#99]
The scenario is like:
```
struct ParentError {
    #[source_code]
    source: String,
    #[related]
    other: Vec<ChildError>,
}
```
I can use `Arc` to copy source code to every child error, but this is a bit inconvenient. Parsers usually only propagate byte range as a span so I have to either wrap every error into another wrapper having source code, or propagate some custom span that includes `Arc<SourceCode>`.

Can handler propagate that source code while rendering or are there any big downsides of that?

**Comment by zkat** [comment]
This can be done pretty easily [by using an error wrapper that "forwards" the `source_code` implementation](https://github.com/nushell/engine-q/blob/8cf4402e6cbfbe850ee47521bedb65c890baba89/crates/nu-cli/src/errors.rs)

Would that work for you? It seemed to work pretty well for engine-q.

**Comment by tailhook** [comment]
This means I should make a manual wrapper with a `related` method kinda like this:
```rust
fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn Diagnostic> + 'a>> {
  Some(self.other.iter().map(|e| ErrorWrapper { source: &self.source, error: e }))
}
```
But it's impossible to do as iterator should return a reference and I can get a reference for the temporary object like above. So it will need to end up something like this:
```rust
struct ParentError {
    #[source_code]
    source: Arc<String>,
    #[related]
    other: Vec<ErrorWrapper<ChildError>>,
}
```
Still having an Arc to clone the source code into every error.
